### ISSUE TITLE
Очередь для матеши

### ISSUE THREAD

**Issue by 1ffycat** [MaxKuklaVod/P3lv1C#13]
Сделать возможность рандомно создавать очередь для матеши.

Важные вопросики:
> - Как обыгрывать отсутствующих/не желающих? Варики:
>     1. Сделать вхождение в очередь по желанию (например, кто-то стартует очередь типа `/qstart` и желающие входят с помощью `/qjoin`, потом создавший формирует очередь через `/qmake` и всех раскидывает рандомно. Или не использовать `/qmake` и просто рандомно распределять каждого присоединившегося
>     2. Сделать возможность удалять из очереди отсутствующих `/qremove` или `/qignore` или отмечать присутствующих (например `/qadd <список ников>`)
>     3. Похуй, сами разберемся
> 
> - Как формировать очередь? Варики
>     1. Рандомно
>     2. По порядку вхождения
>     3. По порядку вхождения и по предпочтению (`/qjoin 1` чтобы попросить быть первым, `/qjoin -1` чтобы попросить быть последним, `/qjoin after @iffycat` чтобы попросить быть после меня)
>
> - Делать ли возможность меняться? `/qswap @iffycat`, обязательно чтобы требовало согласия второго человека
>
> - Давать ли кому-то право модифицировать очередь? Например, чтобы перестраивать в ней желающих или при особых обстоятельствах
>
> - Делать ли автоматическое формирование очереди, если началась пара матеши по расписанию? (звучит круто)
>
> - Не заебался ли я писать эту задачу?
>     1. Да.
>     2. Да.

**Comment by 1ffycat** [comment]
На первый релиз добавлять не буду, ибо много всего продумать надо, а первый релиз скорее сервисный. Если сделаем быстро, выкатим с первым релизом.

**Comment by MaxKuklaVod** [comment]
Это какой-то пиздец
