### ISSUE TITLE
Добавить .dockerfile в корень репы

### ISSUE THREAD

**Issue by 1ffycat** [MaxKuklaVod/P3lv1C#7]
Надо-надо. Надо. И нужно. И надо. У Миши должен быть.

P.S. Надо чтобы по нужде он у всех был, плюс чтобы гх мог сам собирать контейнер и лить в прод.

**Comment by jezvgg** [comment]
Тогда нужно добавить и requirments.txt и сделать общий файл ключей

**Comment by 1ffycat** [comment]
Ключи лучше сохранять в переменные среды (export в линуксе, ENV в докере). Таким образом проще их менять в настройках контейнера

**Comment by m513t20** [comment]
Считайте сделано (я его просто в  .gitignore записал, чтоб лишние файлы не пушить)

**Comment by m513t20** [comment]
готова
